# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :tests do
    run_tests(workspace: "Paces.xcworkspace",
              devices: ["iPhone 6s"],
              scheme: "PacesKitTests")
    run_tests(workspace: "Paces.xcworkspace",
              devices: ["iPhone 6s"],
              scheme: "PacesUITests")
  end

  lane :screenshots do
    capture_screenshots(workspace: "Paces.xcworkspace", scheme: "PacesUITests")
    frame_screenshots(path: "./screenshots")
    # upload_to_app_store
  end

  lane :beta do
    # get_certificates           # invokes cert
    # get_provisioning_profile   # invokes sigh
    increment_version_number(version_number: "1.1")
    increment_build_number(build_number: latest_testflight_build_number + 1,
                           xcodeproj: "Paces.xcodeproj")
    build_app(scheme: "Paces",
              workspace: "Paces.xcworkspace",
              include_bitcode: true)
    upload_to_testflight
  end
  

end
