# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :tests do
    run_tests(workspace: "Paces.xcworkspace",
              devices: ["iPhone 6s"],
              scheme: "PacesKitTests")
  end

  lane :screenshots do
    capture_screenshots(workspace: "Paces.xcworkspace", scheme: "PacesUITests")
    # upload_to_app_store
  end


end
