# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone X",
   "iPhone 6 Plus",
#   "iPhone 6",
#   "iPhone 5s",
   "iPad Pro (12.9-inch)",
   "iPad Pro (9.7-inch)",
#   "Apple TV 1080p"
 ])

 languages([
   "en-US",
#   "de-DE",
 ])

# The name of the scheme which contains the UI Tests
 scheme "PacesUITests"

# Where should the resulting screenshots be stored?
 output_directory "./screenshots"

# remove the '#' to clear all previously generated screenshots before creating new ones
 clear_previous_screenshots true

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot

stop_after_first_error true
number_of_retries 0
concurrent_simulators false